import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        margin_desktop: "48px",
        sm: "8px",
        xl: "32px",
        lg: "24px",
        margin_mobile: "16px",
        gutter: "24px",
        base: "8px",
        xs: "4px",
        md: "16px",
      },
      colors: {
        background: "#0b1326",
        foreground: "#dae2fd",
        surface: "#0b1326",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#c7c4d8",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        outline: "#918fa1",
        "outline-variant": "#464555",
        "surface-tint": "#c3c0ff",
        primary: "#c3c0ff",
        "on-primary": "#1d00a5",
        "primary-container": "#4f46e5",
        "on-primary-container": "#dad7ff",
        "inverse-primary": "#4d44e3",
        secondary: "#d0bcff",
        "on-secondary": "#3c0091",
        "secondary-container": "#571bc1",
        "on-secondary-container": "#c4abff",
        tertiary: "#adc6ff",
        "on-tertiary": "#002e6a",
        "tertiary-container": "#005cc6",
        "on-tertiary-container": "#cedbff",
        error: "#F43F5E",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-fixed": "#0f0069",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#5516be",
        "tertiary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed": "#001a42",
        "on-tertiary-fixed-variant": "#004395",
        "on-background": "#dae2fd",
        "surface-variant": "#2d3449",
        success: "#10B981",
        warning: "#F59E0B",
        "slate-50": "#F8FAFC",
        "slate-400": "#94A3B8",
        "slate-800": "#1E293B",
        "electric-blue": "#60A5FA",
        
        // Keep compat with standard shadcn border/input/ring keys mapping to design tokens
        border: "rgba(255, 255, 255, 0.1)",
        input: "#1E293B",
        ring: "#4f46e5",
      },
    },
  },
  plugins: [],
} satisfies Config;
