"""add_recruiter_fields_to_users"""

from alembic import op
"""add_recruiter_fields_to_users"""

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision = '660c4cb41431'
down_revision = '9df52b48251b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###