"""add_resume_parser_fields"""

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision = '9df52b48251b'
down_revision = '15c44ff778b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('resumes', sa.Column('parser_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parser_version')
    op.drop_column('resumes', 'processed_at')
    # ### end Alembic commands ###