"""Interview analysis API endpoints for SmartHire AI.

Exposes two routes:
    POST /interview/analyze-question  — per-question analysis (called after each answer)
    POST /interview/finalize          — full interview report (called when interview ends)

Authentication: JWT Bearer token verified cryptographically — no DB round-trip.
Both endpoints are stateless (Gemini / Groq only) so they use verify_jwt_only
instead of get_current_active_user to avoid unnecessary database load.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends

from app.core.security.dependencies import verify_jwt_only
from app.schemas.interview import (
    GenerateQuestionsRequest,
    GeneratedQuestionsResponse,
    GenerateNextQuestionRequest,
    GenerateNextQuestionResponse,
    InterviewFinalizeRequest,
    InterviewFinalizeResponse,
    QuestionAnalysisRequest,
    QuestionAnalysisResponse,
)
from app.services.interview_analysis import InterviewAnalysisService
from app.services.interview_finalizer import InterviewFinalizerService
from app.services.interview_question_generator import InterviewQuestionGeneratorService
from app.services.interview_dynamic_question import DynamicQuestionService

router = APIRouter(prefix="/interview", tags=["interview"])


@router.post(
    "/generate-questions",
    response_model=GeneratedQuestionsResponse,
    summary="Generate personalized interview questions from resume + JD",
    description=(
        "Accepts the candidate's resume text and job description. "
        "Uses Gemini 2.5 Flash (with Groq llama-3.3-70b fallback) to generate "
        "tailored interview questions specific to this candidate and role."
    ),
    responses={
        200: {"description": "Questions generated successfully."},
        401: {"description": "Missing or invalid JWT Bearer token."},
        502: {"description": "Both LLM APIs failed."},
        503: {"description": "No LLM API key configured on the server."},
    },
)
async def generate_questions(
    payload: GenerateQuestionsRequest,
    _token_payload: dict = Depends(verify_jwt_only),
) -> GeneratedQuestionsResponse:
    """Generate personalized interview questions via LLM."""
    service = InterviewQuestionGeneratorService()
    return await service.generate(payload)


@router.post(
    "/generate-next-question",
    response_model=GenerateNextQuestionResponse,
    summary="Generate the next contextual question dynamically during an interview",
    description=(
        "Accepts the full conversation history (prior Q&A pairs with scores) and "
        "uses a dedicated question-generation LLM (separate from the analysis LLM) "
        "to produce the next contextually relevant interview question. "
        "This enables truly dynamic, human-like interview conversations."
    ),
    responses={
        200: {"description": "Next question generated successfully."},
        401: {"description": "Missing or invalid JWT Bearer token."},
        502: {"description": "Both LLM APIs failed."},
        503: {"description": "No LLM API key configured on the server."},
    },
)
async def generate_next_question(
    payload: GenerateNextQuestionRequest,
    _token_payload: dict = Depends(verify_jwt_only),
) -> GenerateNextQuestionResponse:
    """Generate the next dynamic follow-up question using conversation context."""
    service = DynamicQuestionService()
    return await service.generate_next(payload)

@router.post(
    "/analyze-question",
    response_model=QuestionAnalysisResponse,
    summary="Analyse a single interview question-answer pair",
    description=(
        "Accepts the question text, speech-to-text transcript, and MediaPipe "
        "vision metrics for a single answered question. Returns per-dimension "
        "scores, strengths, improvements, and feedback generated by Gemini "
        "(with automatic Groq llama-3.3-70b fallback)."
    ),
    responses={
        200: {"description": "Analysis completed successfully."},
        401: {"description": "Missing or invalid JWT Bearer token."},
        422: {"description": "LLM returned an unexpected response format."},
        502: {"description": "Upstream LLM API error."},
        503: {"description": "No LLM API key is configured on the server."},
    },
)
async def analyze_question(
    payload: QuestionAnalysisRequest,
    _token_payload: dict = Depends(verify_jwt_only),
) -> QuestionAnalysisResponse:
    """Run per-question analysis using Gemini → Groq fallback.

    Args:
        payload:       Question text, transcript, and vision metrics.
        _token_payload: Decoded JWT claims (injected; confirms caller is authenticated).

    Returns:
        QuestionAnalysisResponse with scores and actionable feedback.
    """
    service = InterviewAnalysisService()
    return await service.analyze(payload)


@router.post(
    "/finalize",
    response_model=InterviewFinalizeResponse,
    summary="Finalise the interview and generate a holistic report",
    description=(
        "Accepts the full list of per-question analysis results and returns a "
        "holistic candidate report: overall score, recommendation, top "
        "strengths/improvements, weak-question breakdown, and communication "
        "and body-language summaries — generated by Gemini with Groq fallback."
    ),
    responses={
        200: {"description": "Finalisation completed successfully."},
        401: {"description": "Missing or invalid JWT Bearer token."},
        422: {"description": "LLM returned an unexpected response format."},
        502: {"description": "Upstream LLM API error."},
        503: {"description": "No LLM API key is configured on the server."},
    },
)
async def finalize_interview(
    payload: InterviewFinalizeRequest,
    _token_payload: dict = Depends(verify_jwt_only),
) -> InterviewFinalizeResponse:
    """Aggregate all question results and generate a holistic interview report.

    Args:
        payload:       All question analysis results + candidate metadata.
        _token_payload: Decoded JWT claims (injected; confirms caller is authenticated).

    Returns:
        InterviewFinalizeResponse with overall scores, recommendation, and
        weak-question breakdown.
    """
    service = InterviewFinalizerService()
    return await service.finalize(payload)
